### ISSUE TITLE
RQ-dashboard is incompatible with click>=8.0.1

### ISSUE THREAD

**Issue by areedee** [fcakyon/flask-redis-docker#1]
I wasn't able to get the template to work until I added the following to requirements.txt:
`click==7.1.2`

It seems rq-dashboard is aware of the issue:
[https://github.com/Parallels/rq-dashboard/pull/385](https://github.com/Parallels/rq-dashboard/pull/385)

**Comment by fcakyon** [comment]
@areedee thanks a lot for mentioning! fixed the click version: https://github.com/fcakyon/flask-redis-docker/blob/master/project/requirements.txt
